### ISSUE TITLE
the updated content of depthcrafter v1.0.1

### ISSUE THREAD

**Issue by zhenzhiwang** [Tencent/DepthCrafter#46]
Thanks for sharing your great work on depth estimation. I am curious about the reason of performance gain and the speed increase. From the code, it seems that the guidance_scale and the num_inference_step has been changed. But how the model could achieve both better performance and inference speed? Did you re-train your model with some other techniques?

I will really appreciate it if you could share ideas to improve the model. Thank you!

**Comment by wbhu** [comment]
Hi, we didn't retrain the model, so the weights are the same as the previous version. We suppose the reason is that video-to-depth tasks are more deterministic than img-to-video, so the num_inference_step could be only 5, and increasing it leads to a saturated performance. Please refer to our updated paper (supp part) for more details.

**Comment by zhenzhiwang** [comment]
> Hi, we didn't retrain the model, so the weights are the same as the previous version. We suppose the reason is that video-to-depth tasks are more deterministic than img-to-video, so the num_inference_step could be only 5, and increasing it leads to a saturated performance. Please refer to our updated paper (supp part) for more details.

Thank you for the explanation. So v1.0.1 means only changing the num_inference_step to be 5 and guidance_scale to be 1, am I right?

**Comment by wbhu** [comment]
Yes

**Comment by zhenzhiwang** [comment]
Thank you very much!
